export default { 
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
    REGISTER_USER_STARTED: 'REGISTER_USER_STARTED',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
    ALREADY_LOGGEDIN_SUCCESS: 'ALREADY_LOGGEDIN_SUCCESS',
    ALREADY_LOGGEDIN_FAILED: 'ALREADY_LOGGEDIN_FAILED',
    READ_FROM_SESSION: 'READ_FROM_SESSION',
    SELECT_CHAT: 'SELECT_CHAT',
    UPDATE_CHAT_LIST: 'UPDATE_CHAT_LIST'
 };